#mt_token = token#uuid 例如：mt_token = Agxxxxx#0000xxxxxxxx
mt_token = 
#mtgsig算法服务器 
#mtgsig_server = https://xxx.xxx.xxx/api/mtgsig
mtgsig_server =
#mtgsig算法服务器认证token
#mtgsig_token = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
mtgsig_token =
